import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'he';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.funDay': 'Fun Day for Companies',
    'nav.vipTours': 'VIP Tours for Guests',
    'nav.odt': 'ODT Team Building',
    'nav.contact': 'Contact',
    'nav.accessibility': 'Accessibility',
    'nav.accessibilityStatement': 'Accessibility Statement',
    'nav.bookTour': 'Book Tour',
    'nav.adminLogin': 'Admin Login',
    'nav.myAccount': 'My Account',
    'nav.dashboard': 'Dashboard',
    'nav.knowledgeBase': 'Knowledge Base',
    'nav.signOut': 'Sign Out',
    'nav.openMenu': 'Open menu',
    'nav.closeMenu': 'Close menu',
    'nav.accountMenu': 'Account menu',
    'nav.brandName': 'Simcha',
    'nav.quiz': 'Team Quiz',
    'nav.keywords': 'Keywords',
    'nav.adminChat': 'Admin Chat',
    'nav.leadManagement': 'Lead Management',
    'nav.editAIResponses': 'Edit AI Responses',
    'nav.aiSettings': 'AI Settings (Text)',

    // Hero
    'hero.title': 'A Unique, Empowering & Unforgettable Group Experience',
    'hero.subtitle': 'In beautiful Northern Israel — the valleys, Gilboa Ridge, Harod Springs, the Galilee & around the Sea of Galilee',
    'hero.description': 'A fun, meaningful day combining history, nature, team-building, and great memories for your company.',
    'hero.categories': '🔥 Adventures  |  💧 Nature  |  🏛️ History  |  🍷 Wine & Culinary  |  ⚡ Sports  |  🎨 Creative  |  🌿 Wellness  |  🤝 Teamwork',
    'hero.chatAgent': 'Chat with Smart Agent',
    'hero.bookTour': 'Book a Tour',
    'hero.contactUs': 'Contact Us',
    'hero.whatsapp': 'WhatsApp',
    'hero.generateAI': 'Generate AI Background',
    'hero.scrollDown': 'Scroll down for more content',

    // Contact
    'contact.title': 'Get in Touch',
    'contact.name': 'Full Name',
    'contact.email': 'Email',
    'contact.phone': 'Phone',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.success': 'Message sent! We\'ll get back to you soon.',
    'contact.error': 'Error sending message. Please try again.',
    'contact.whatsapp': 'WhatsApp',
    'contact.phoneLabel': 'Phone',
    'contact.emailLabel': 'Email',

    // Footer
    'footer.brandName': 'Simcha',
    'footer.description': 'Unforgettable group experiences in Northern Israel — combining history, nature, team-building, and great memories.',
    'footer.contact': 'Contact Us',
    'footer.quickLinks': 'Quick Links',
    'footer.chooseDay': 'Choose Your Fun Day',
    'footer.vipTours': 'VIP Tours',
    'footer.odtActivities': 'ODT Team Building Activities',
    'footer.contactUs': 'Contact Us',
    'footer.accessibilityStatement': 'Accessibility Statement',
    'footer.rights': `© ${new Date().getFullYear()} Simcha. All rights reserved.`,

    // Why Choose Us
    'why.title': 'Why Choose Simcha?',
    'why.certified': 'Professional & Certified',
    'why.certifiedDesc': 'Licensed tour guide with years of experience',
    'why.custom': 'Tailored Experiences',
    'why.customDesc': 'Designed for corporate groups, hi-tech companies, employee committees & professional companies',
    'why.safe': 'Safe & Refreshing',
    'why.safeDesc': 'Perfect for the hot Israeli summer',
    'why.fullService': 'Full Service',
    'why.fullServiceDesc': 'All logistics handled from start to finish',

    // ODT
    'odt.whatIsODT': 'What is ODT?',
    'odt.clickHere': 'Click here',
    'odt.description': 'Outdoor Development Training uses nature-based challenges to strengthen teamwork, leadership, and communication skills.',
    'odt.seeActivities': 'Click to see 15 types of ODT activities with realistic images',
    'odt.benefits': 'ODT Benefits',
    'odt.benefit1': 'Enhanced team collaboration',
    'odt.benefit2': 'Leadership development',
    'odt.benefit3': 'Problem-solving skills',
    'odt.benefit4': 'Trust building',
    'odt.whatsapp': 'WhatsApp',

    // Service Cards
    'services.title': 'Our Services',
    'services.subtitle': 'Choose the perfect experience — daily tours, VIP experiences, or corporate team-building events',
    'services.dailyTitle': 'Daily Tours',
    'services.dailyShort': 'Guided experiences in the Gilboa and Beit She\'an Valley region',
    'services.dailyLong': 'A full day of historical and stunning natural experiences. Perfect for families, friend groups, and work teams.',
    'services.dailyFeature1': 'Choice of 3 customized tour packages',
    'services.dailyFeature2': 'Professional and experienced guide',
    'services.dailyFeature3': 'Personalized for families and groups',
    'services.dailyFeature4': 'Historical sites and stunning viewpoints',
    'services.dailyFeature5': 'Visit crystal-clear springs',
    'services.dailyFeature6': 'Meal included in the area',
    'services.dailyHighlight1': 'Tour duration: 7-8 hours',
    'services.dailyHighlight2': 'Suitable for ages 8-88+',
    'services.dailyHighlight3': 'Guide included, transport not included',
    'services.dailyCTA': 'Choose Your Tour',
    'services.vipTitle': 'VIP Tours',
    'services.vipShort': 'Premium personalized experience with luxury service',
    'services.vipLong': 'An exclusive, fully customized tour. Personal service, luxury vehicles, and top-tier culinary experiences.',
    'services.vipFeature1': '100% personalized itinerary',
    'services.vipFeature2': 'Private luxury vehicles with driver',
    'services.vipFeature3': 'Unique boutique culinary experiences',
    'services.vipFeature4': 'Dedicated private guide throughout the tour',
    'services.vipFeature5': 'Access to exclusive sites',
    'services.vipFeature6': 'Full concierge service',
    'services.vipHighlight1': '1-45 participants',
    'services.vipHighlight2': 'Full coordination to your schedule',
    'services.vipHighlight3': 'Option to include overnight stay',
    'services.vipCTA': 'Plan a VIP Tour',
    'services.odtTitle': 'ODT for Organizations',
    'services.odtShort': 'Outdoor Development Training — team building for companies',
    'services.odtLong': 'Professional ODT program combining challenges, team-building activities, and nature experiences. Suitable for companies of all sizes.',
    'services.odtFeature1': 'Event planning tailored to organizational needs',
    'services.odtFeature2': 'Professional team-building activities with certified facilitators',
    'services.odtFeature3': 'Suitable for groups of 10-200 participants',
    'services.odtFeature4': 'Combination of physical activity and meaningful content',
    'services.odtFeature5': 'Focus on teamwork and leadership',
    'services.odtFeature6': 'Option to include lectures and workshops',
    'services.odtHighlight1': 'Event duration: half day to two days',
    'services.odtHighlight2': 'Professional equipment included',
    'services.odtHighlight3': 'Guide team and support staff',
    'services.odtCTA': 'Contact Us to Plan',
    'services.whatIncluded': 'What\'s Included?',
    'services.keyPoints': 'Key Points',
    'services.clickDetails': 'Click for full details',

    // Testimonials
    'testimonials.title': 'What Our Clients Say',
    'testimonials.subtitle': 'Thousands of companies trust us to create unforgettable experiences',
    'testimonials.featured': '⭐ Featured Review',

    // Booking
    'booking.title': 'Book a Tour',
    'booking.subtitle': 'Fill in the details and a representative will contact you',
    'booking.name': 'Full Name *',
    'booking.email': 'Email *',
    'booking.phone': 'Phone *',
    'booking.company': 'Company (optional)',
    'booking.participants': 'Number of Participants *',
    'booking.tourDate': 'Tour Date *',
    'booking.selectDate': 'Select date',
    'booking.duration': 'Tour Duration *',
    'booking.selectDuration': 'Select duration',
    'booking.halfDay': 'Half Day (4 hours)',
    'booking.fullDay': 'Full Day (8 hours)',
    'booking.twoDays': '2 Days',
    'booking.threeDays': '3 Days',
    'booking.custom': 'Custom',
    'booking.language': 'Tour Guide Language *',
    'booking.selectLanguage': 'Select language',
    'booking.specialRequests': 'Special Requests (optional)',
    'booking.specialPlaceholder': 'What would you like to experience, see, or expect on the tour?',
    'booking.submit': 'Submit Booking',
    'booking.submitting': 'Submitting...',
    'booking.success': 'Booking submitted successfully!',
    'booking.successDesc': 'A representative will contact you soon',
    'booking.error': 'Error',
    'booking.errorDesc': 'An error occurred. Please try again.',
    'booking.dateError': 'Please select a tour date',

    // MegaMenu
    'mega.home.desc': 'Discover the Gilboa and Jordan Valley',
    'mega.home.h1': 'Panoramic views',
    'mega.home.h2': 'Unique experiences',
    'mega.home.h3': 'Professionalism & quality',
    'mega.funDay.desc': 'A full day of team-building activities',
    'mega.funDay.h1': '100+ activities',
    'mega.funDay.h2': 'Personalized Quiz',
    'mega.funDay.h3': 'Nature experiences',
    'mega.vip.desc': 'Personalized VIP experiences',
    'mega.vip.h1': 'Luxury service',
    'mega.vip.h2': 'Language guides',
    'mega.vip.h3': 'Personal customization',
    'mega.odt.desc': 'Advanced team-building programs',
    'mega.odt.h1': 'Team building',
    'mega.odt.h2': 'Professional challenges',
    'mega.odt.h3': 'Meaningful experience',
    'mega.contact.desc': 'Happy to help and advise',
    'mega.contact.h1': 'Personal service',
    'mega.contact.h2': 'Quick response',
    'mega.contact.h3': 'Professional consultation',
    'mega.goTo': 'Go to',

    // Exit Intent Modal
    'exit.title': 'Have questions?',
    'exit.needAdvice': 'Need more advice?',
    'exit.speakWith': 'Speak directly with',
    'exit.expertAvailable': 'Our tour expert — available now!',
    'exit.whatsapp': 'Send a WhatsApp message now',
    'exit.callDirect': 'Call directly:',
    'exit.sendEmail': 'Send email',
    'exit.continueBrowsing': 'Continue browsing',
    'exit.helpTip': '💡 We\'re here to help! Don\'t hesitate to reach out',

    // Emergency Contact
    'emergency.talkToOwner': 'Talk to the owner',
    'emergency.needHelp': 'Need help? Talk to me!',
    'emergency.availableNow': 'Available now',
    'emergency.tourExpert': 'Our tour expert',
    'emergency.personalMessage': '💬 I\'m here for you! If you have questions, want guidance on the site, or personal advice — don\'t hesitate to contact me directly. I\'ll gladly respond!',
    'emergency.contactMethods': 'Contact methods:',
    'emergency.whatsapp': 'Send a WhatsApp message',
    'emergency.whatsappSub': 'Recommended — quick response!',
    'emergency.callDirect': 'Call directly',
    'emergency.sendEmail': 'Send email',
    'emergency.availability': 'Availability hours',
    'emergency.sunThur': 'Sun-Thu: 08:00-20:00',
    'emergency.friday': 'Fri: 08:00-14:00',
    'emergency.urgent': 'For urgent cases — even outside these hours!',
    'emergency.goal': '🎯 My goal: Help you find the perfect experience!',

    // Protected Route
    'protected.loading': 'Loading...',
    'protected.redirecting': 'Redirecting to login...',
    'protected.noPermission': 'No Permission',
    'protected.noAdminAccess': 'You don\'t have admin permissions to view this page',

    // Testimonial Submission Form
    'testimonialForm.title': 'Share Your Experience',
    'testimonialForm.subtitle': 'We\'d love to hear about your tour with us',
    'testimonialForm.name': 'Full Name *',
    'testimonialForm.namePlaceholder': 'Full name',
    'testimonialForm.email': 'Email',
    'testimonialForm.company': 'Company',
    'testimonialForm.companyPlaceholder': 'Company name',
    'testimonialForm.tourType': 'Tour Type',
    'testimonialForm.tourTypePlaceholder': 'e.g., Team building, VIP, ODT',
    'testimonialForm.rating': 'Rating *',
    'testimonialForm.testimonial': 'Testimonial *',
    'testimonialForm.testimonialPlaceholder': 'Tell us about your experience...',
    'testimonialForm.submit': 'Submit Testimonial',
    'testimonialForm.submitting': 'Submitting...',
    'testimonialForm.success': 'Thank you!',
    'testimonialForm.successDesc': 'Your testimonial has been submitted and will be published after approval.',
    'testimonialForm.error': 'Error',
    'testimonialForm.errorDesc': 'An error occurred while submitting. Please try again.',

    // Accessibility Widget
    'a11y.skipToContent': 'Skip to main content',
    'a11y.openMenu': 'Open accessibility menu',
    'a11y.settings': 'Accessibility Settings',
    'a11y.fontSize': 'Text Size',
    'a11y.decreaseFont': 'Decrease text',
    'a11y.increaseFont': 'Increase text',
    'a11y.highContrast': 'High Contrast',
    'a11y.grayscale': 'Grayscale',
    'a11y.highlightLinks': 'Highlight Links',
    'a11y.stopAnimations': 'Stop Animations',
    'a11y.readableFont': 'Readable Font',
    'a11y.largeCursor': 'Large Cursor',
    'a11y.readingGuide': 'Reading Guide',
    'a11y.reset': 'Reset Settings',
    'a11y.statement': 'Accessibility Statement',

    // Live Chat Widget
    'liveChat.title': 'Live Chat — Support',
    'liveChat.connected': 'Connected now',
    'liveChat.liveChat': 'Live Chat',
    'liveChat.new': 'new',
    'liveChat.hello': 'Hello! 👋',
    'liveChat.helpMessage': 'We\'re here to help. Enter your name to start a chat',
    'liveChat.namePlaceholder': 'Your name...',
    'liveChat.startChat': 'Start Chat',
    'liveChat.nameRequired': 'Name required',
    'liveChat.enterName': 'Please enter your name to start a chat',
    'liveChat.messagePlaceholder': 'Write a message...',
    'liveChat.autoResponse': '🤖 Instant auto-reply • 👤 Real agent available soon',
    'liveChat.agentNeeded': '📞 A human agent will get back to you soon',
    'liveChat.agentNeededDesc': 'Your question has been forwarded to our agent',
    'liveChat.sendError': 'Send error',
    'liveChat.sendErrorDesc': 'Could not send message. Please try again',
    'liveChat.startError': 'Error',
    'liveChat.startErrorDesc': 'Could not start the chat. Please try again',
    'liveChat.nameRequiredDesc': 'Please enter your name to start a chat',
    'liveChat.system': 'System',
    'liveChat.welcomeMessage': 'Hello {name}! 👋\n\nWe\'re here to help.\n\n🤖 Smart auto-responder will answer your initial questions\n👤 A real agent will join if needed\n\nFeel free to ask your question!',
    'liveChat.error': 'Error',
    'liveChat.errorStartDesc': 'Could not start the chat. Please try again',
    'liveChat.humanAgentTitle': '📞 A human agent will get back to you soon',
    'liveChat.humanAgentDesc': 'Your question has been forwarded to our agent',

    // PublicFAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Find answers to the most common questions',
    'faq.loading': 'Loading FAQs...',
    'faq.notFound': 'Didn\'t find what you were looking for?',
    'faq.contactUs': 'Contact us',
    'faq.general': 'General',

    // Auth
    'auth.loading': 'Loading...',
    'auth.title': 'Simcha — Admin Panel',
    'auth.subtitle': 'Sign in or register to access the system',
    'auth.loginTab': 'Login',
    'auth.signupTab': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.fullName': 'Full Name',
    'auth.loginButton': 'Sign In',
    'auth.loggingIn': 'Signing in...',
    'auth.signupButton': 'Sign Up',
    'auth.signingUp': 'Signing up...',
    'auth.namePlaceholder': 'John Doe',
    'auth.passwordPlaceholder': 'At least 6 characters',
    'auth.invalidEmail': 'Invalid email address',
    'auth.passwordMin': 'Password must be at least 6 characters',
    'auth.nameMin': 'Name must be at least 2 characters',

    // Accessibility Statement
    'a11yStatement.title': 'Accessibility Statement',
    'a11yStatement.metaTitle': 'Accessibility Statement | Simcha',
    'a11yStatement.metaDesc': 'Accessibility statement for the Simcha website',
    'a11yStatement.subtitle': 'Simcha is committed to making this website accessible to people with disabilities',
    'a11yStatement.commitmentTitle': 'Commitment to Accessibility',
    'a11yStatement.commitmentP1': 'The Simcha website works to make the site accessible to people with disabilities in accordance with Israeli Standard SI 5568 and WCAG 2.1 Level AA guidelines.',
    'a11yStatement.commitmentP2': 'We believe every person has a right to equal access to information and services, and have invested significant efforts in making the site accessible to all users.',
    'a11yStatement.featuresTitle': 'Accessibility Features',
    'a11yStatement.feature1': 'Text size adjustment — option to enlarge or reduce text',
    'a11yStatement.feature2': 'High contrast mode for improved readability',
    'a11yStatement.feature3': 'Grayscale mode for color sensitivity',
    'a11yStatement.feature4': 'Link highlighting for easy identification',
    'a11yStatement.feature5': 'Option to stop animations',
    'a11yStatement.feature6': 'Readable font — switch to a clearer font',
    'a11yStatement.feature7': 'Enlarged mouse cursor',
    'a11yStatement.feature8': 'Reading ruler for line tracking',
    'a11yStatement.feature9': 'Full keyboard navigation',
    'a11yStatement.feature10': 'Image descriptions (alt text) for screen readers',
    'a11yStatement.feature11': 'Standard semantic page structure',
    'a11yStatement.feature12': '"Skip to content" link for quick navigation',
    'a11yStatement.menuTitle': 'Using the Accessibility Menu',
    'a11yStatement.menuP1': 'The accessibility menu is located at the accessibility button on the left side of the screen (person icon). Clicking the button will open the menu where you can enable or disable various settings.',
    'a11yStatement.menuP2': 'Settings are saved automatically and will apply on future visits.',
    'a11yStatement.limitationsTitle': 'Known Limitations',
    'a11yStatement.limitationsP': 'Despite our efforts to make the site fully accessible, some parts may not yet be completely accessible. We continue to work on improving accessibility.',
    'a11yStatement.limitation1': 'Some images may lack full descriptions',
    'a11yStatement.limitation2': 'User-generated content (such as testimonials) may not be fully accessible',
    'a11yStatement.limitation3': 'Interactive maps may have limited accessibility',
    'a11yStatement.contactTitle': 'Contact Us About Accessibility',
    'a11yStatement.contactP': 'Encountered an accessibility issue? We\'d love to hear from you and address it promptly:',
    'a11yStatement.lastUpdate': 'Last Update',
    'a11yStatement.lastUpdateText': 'This accessibility statement was last updated on:',

    // ChooseYourDay
    'chooseDay.title': 'Fun Day & Team Building — ~100 Tours & Attractions to Choose From',
    'chooseDay.subtitle': 'Choose your favorite attractions or sites from the categories',
    'chooseDay.morningAdventure': 'Morning Adventure',
    'chooseDay.springsRelax': 'Springs Relaxation',
    'chooseDay.heritageMeeting': 'Heritage Meeting',
    'chooseDay.culinaryCelebration': 'Culinary Celebration',
    'chooseDay.chronologicalTip': 'Combine them chronologically to create a full day plan (09:00 - 17:00)',
    'chooseDay.category': 'Category',
    'chooseDay.selected': 'selected',
    'chooseDay.selectUpTo5': 'Select up to 5 activities, together we\'ll determine the best fit considering timing, field options and weather',
    'chooseDay.recommended': 'Recommended',
    'chooseDay.showing': 'Showing',
    'chooseDay.recommendedOf': 'recommended activities of',
    'chooseDay.otherOption': 'Other option (if not listed):',
    'chooseDay.otherPlaceholder': 'Describe an activity not on the list...',
    'chooseDay.summaryTitle': 'Your Fun Day Selection Summary',
    'chooseDay.summarySubtitle': 'Please fill in the following details so we can get back to you',
    'chooseDay.fullName': 'Full Name',
    'chooseDay.fullNamePlaceholder': 'Enter full name',
    'chooseDay.emailAddress': 'Email Address',
    'chooseDay.emailPlaceholder': 'Enter email address',
    'chooseDay.companyName': 'Company Name',
    'chooseDay.companyPlaceholder': 'Enter company name',
    'chooseDay.whatsappNumber': 'WhatsApp Number',
    'chooseDay.whatsappPlaceholder': 'Enter WhatsApp number',
    'chooseDay.officeNumber': 'Office Number',
    'chooseDay.officePlaceholder': 'Enter office number',
    'chooseDay.participantCount': 'Estimated Participants',
    'chooseDay.participantPlaceholder': 'How many people will attend?',
    'chooseDay.tourType': 'Tour Type',
    'chooseDay.oneDay': 'One Day',
    'chooseDay.multipleDays': 'Multiple Days',
    'chooseDay.suggestedDate': 'Suggested Event Date',
    'chooseDay.selectDatePlaceholder': 'Select date',
    'chooseDay.specialComments': 'Special requests and wishes from guests',
    'chooseDay.specialPlaceholder': 'Share additional details, special wishes or event reason...',
    'chooseDay.languageLabel': 'Languages: specify the language required for your guests',
    'chooseDay.languagePlaceholder': 'e.g., English, Spanish, French, German...',
    'chooseDay.sendToEmail': 'Send to Email',
    'chooseDay.sending': 'Sending...',
    'chooseDay.missingFields': 'Missing details',
    'chooseDay.missingFieldsDesc': 'Please fill in all required fields (name, email, company, WhatsApp number)',
    'chooseDay.invalidEmail': 'Invalid email',
    'chooseDay.invalidEmailDesc': 'Please enter a valid email address',
    'chooseDay.sentSuccess': 'Sent successfully!',
    'chooseDay.sentSuccessDesc': 'Your preferences have been sent. We\'ll get back to you soon.',
    'chooseDay.sendError': 'Sending error',
    'chooseDay.sendErrorDesc': 'An error occurred while sending. Please try again later.',
    'chooseDay.selectedForYou': 'Activities selected especially for you',
    'chooseDay.basedOnDNA': 'Based on your team\'s DNA:',
    'chooseDay.changePreferences': 'Change preferences',
    'chooseDay.showAllActivities': 'Show all activities',
    'chooseDay.showingAll': 'Showing all activities.',
    'chooseDay.backToRecommended': 'Back to recommended activities',
    'chooseDay.highlyRecommended': 'Highly recommended',
    'chooseDay.required': '*',

    // VIP Tours
    'vip.badge': 'VIP Tours — Up to 19 travelers',
    'vip.title': 'Special VIP Tour for International Guests',
    'vip.description': 'Your company is hosting international guests? Simcha can host them on a VIP tour in a luxurious air-conditioned vehicle and provide an unforgettable tour experience across Israel.',
    'vip.features': 'For groups of 1-19 travelers • Professional driver and expert guide • Luxurious AC vehicle • Customized routes',
    'vip.vehicleVIP': 'VIP AC Vehicle',
    'vip.professionalGuide': 'Professional Guide',
    'vip.customRoute': 'Customized Route',
    'vip.selectTitle': 'Choose Your Preferred Region and Sites',
    'vip.selectSubtitle': 'List of 50+ recommended sites across Israel, organized by geographic region — north to south',
    'vip.selectNote': 'The list includes historical, natural, religious and cultural sites, considered among the most important and fascinating in the country',
    'vip.selectUpTo5': 'Select up to 5 sites, together we\'ll determine the best fit considering timing, field options and weather',
    'vip.selectedCount': 'selected',
    'vip.summaryTitle': 'Your VIP Tour Selection Summary',
    'vip.sendToEmail': 'Send to Email',
    'vip.sending': 'Sending...',
    'vip.sitesSelected': 'sites selected',
    'vip.contactTitle': 'Contact Details',
    'vip.fullName': 'Full Name *',
    'vip.fullNamePlaceholder': 'Enter your full name',
    'vip.email': 'Email *',
    'vip.companyName': 'Company Name *',
    'vip.companyPlaceholder': 'Enter company name',
    'vip.whatsappNumber': 'WhatsApp Number *',
    'vip.officeNumber': 'Office Number',
    'vip.participantCount': 'Number of Participants',
    'vip.participantPlaceholder': 'Number of guests',
    'vip.numberOfDays': 'Number of Days',
    'vip.selectDays': 'Select number of days',
    'vip.suggestedDate': 'Suggested Date',
    'vip.selectDate': 'Select date',
    'vip.tourLanguage': 'Tour Language',
    'vip.tourLanguagePlaceholder': 'e.g., Hebrew, English, etc.',
    'vip.specialComments': 'Special requests and wishes from guests',
    'vip.specialPlaceholder': 'Share details, special wishes or event reason...',
    'vip.missingFields': 'Missing details',
    'vip.missingFieldsDesc': 'Please fill in all required fields (name, email, company, WhatsApp number)',
    'vip.invalidEmail': 'Invalid email',
    'vip.invalidEmailDesc': 'Please enter a valid email address',
    'vip.sentSuccess': 'Preferences sent successfully!',
    'vip.sentSuccessDesc': 'We\'ll contact you soon',
    'vip.sendError': 'Sending error',
    'vip.sendErrorDesc': 'An error occurred. Please try again later.',
  },
  he: {
    // Navigation
    'nav.home': 'בית',
    'nav.funDay': 'יום כייף וגיבוש לחברות',
    'nav.vipTours': 'טיולי VIP לאורחי חברות מחו״ל',
    'nav.odt': 'גיבוש ODT',
    'nav.contact': 'צור קשר',
    'nav.accessibility': 'נגישות',
    'nav.accessibilityStatement': 'הצהרת נגישות',
    'nav.bookTour': 'הזמן סיור',
    'nav.adminLogin': 'כניסת מנהלים',
    'nav.myAccount': 'חשבון שלי',
    'nav.dashboard': 'לוח בקרה',
    'nav.knowledgeBase': 'מאגר ידע',
    'nav.signOut': 'התנתק',
    'nav.openMenu': 'פתח תפריט',
    'nav.closeMenu': 'סגור תפריט',
    'nav.accountMenu': 'תפריט חשבון',
    'nav.brandName': 'שמחה',
    'nav.quiz': 'חידון צוות',
    'nav.keywords': 'מילות מפתח',
    'nav.adminChat': 'צ\'אט מנהל',
    'nav.leadManagement': 'ניהול לידים',
    'nav.editAIResponses': 'עריכת תגובות AI',
    'nav.aiSettings': 'הגדרות AI (טקסטים)',

    // Hero
    'hero.title': 'חוויה קבוצתית מיוחדת, בונה ובלתי נשכחת',
    'hero.subtitle': 'בצפון א״י היפה ובלב העמקים, רכס הגלבוע, עמק המעיינות, הגליל וסובב כנרת',
    'hero.description': 'יום חווייתי, מהנה ומשמעותי שמשלב היסטוריה, טבע, גיבוש, והרבה זיכרונות טובים לחברה שלכם.',
    'hero.categories': '🔥 הרפתקאות  |  💧 טבע  |  🏛️ דברי הימים  |  🍷 יין ואומנות הבישול  |  ⚡ ספורט  |  🎨 יצירה  |  🌿 בריאות  |  🤝 צוותיות',
    'hero.chatAgent': 'שוחח עם הסוכן החכם',
    'hero.bookTour': 'הזמן סיור',
    'hero.contactUs': 'צור קשר',
    'hero.whatsapp': 'וואטסאפ',
    'hero.generateAI': 'צור תמונת רקע ב-AI',
    'hero.scrollDown': 'גלול למטה לתוכן נוסף',

    // Contact
    'contact.title': 'צור קשר',
    'contact.name': 'שם מלא',
    'contact.email': 'דוא"ל',
    'contact.phone': 'טלפון',
    'contact.message': 'הודעה',
    'contact.send': 'שלח הודעה',
    'contact.sending': 'שולח...',
    'contact.success': 'ההודעה נשלחה! נחזור אליך בקרוב.',
    'contact.error': 'שגיאה בשליחת ההודעה. אנא נסה שוב.',
    'contact.whatsapp': 'וואטסאפ',
    'contact.phoneLabel': 'טלפון',
    'contact.emailLabel': 'אימייל',

    // Footer
    'footer.brandName': 'שמחה',
    'footer.description': 'חוויות קבוצתיות בלתי נשכחות בצפון ישראל — משלב היסטוריה, טבע, גיבוש, והרבה זיכרונות טובים.',
    'footer.contact': 'צור קשר',
    'footer.quickLinks': 'קישורים מהירים',
    'footer.chooseDay': 'ביחרו את יום הכייף שלכם',
    'footer.vipTours': 'טיולי VIP',
    'footer.odtActivities': 'פעילויות גיבוש ODT',
    'footer.contactUs': 'צור קשר',
    'footer.accessibilityStatement': 'הצהרת נגישות',
    'footer.rights': `© ${new Date().getFullYear()} שמחה. כל הזכויות שמורות.`,

    // Why Choose Us
    'why.title': 'למה לבחור בשמחה?',
    'why.certified': 'מקצועי ומוסמך',
    'why.certifiedDesc': 'מדריך טיולים מורשה עם שנות ניסיון',
    'why.custom': 'חוויות מותאמות אישית',
    'why.customDesc': 'מעוצב במיוחד לקבוצות עסקיות, חברות הי טק, ועדי עובדים וחברות מקצועיות',
    'why.safe': 'בטוח ומרענן',
    'why.safeDesc': 'מושלם לקיץ הישראלי החם',
    'why.fullService': 'שירות מלא',
    'why.fullServiceDesc': 'כל הלוגיסטיקה מטופלת מתחילה ועד סוף',

    // ODT
    'odt.whatIsODT': 'מהו ODT?',
    'odt.clickHere': 'לחץ כאן',
    'odt.description': 'אימון פיתוח חוץ משתמש באתגרים מבוססי טבע כדי לחזק עבודת צוות, מנהיגות ומיומנויות תקשורת.',
    'odt.seeActivities': 'לחץ כדי לראות 15 סוגי פעילויות ODT עם תמונות ריאליסטיות',
    'odt.benefits': 'ODT יתרונות',
    'odt.benefit1': 'שיתוף פעולה צוותי משופר',
    'odt.benefit2': 'פיתוח מנהיגות',
    'odt.benefit3': 'מיומנויות פתרון בעיות',
    'odt.benefit4': 'בניית אמון',
    'odt.whatsapp': 'וואטסאפ',

    // Service Cards
    'services.title': 'השירותים שלנו',
    'services.subtitle': 'בחר את החוויה המושלמת עבורך - סיורים יומיים, חוויות VIP, או אירועי גיבוש לארגונים',
    'services.dailyTitle': 'סיורים יומיים',
    'services.dailyShort': 'חוויות מודרכות באזור הגלבוע ועמק בית שאן',
    'services.dailyLong': 'יום מלא בחוויות היסטוריות וטבעיות מרהיבות. מתאים למשפחות, קבוצות חברים, וצוותי עבודה.',
    'services.dailyFeature1': 'בחירה מ-3 חבילות סיור מותאמות',
    'services.dailyFeature2': 'מדריך מקצועי ומנוסה',
    'services.dailyFeature3': 'התאמה אישית למשפחות וקבוצות',
    'services.dailyFeature4': 'אתרים היסטוריים ותצפיות נוף מדהימות',
    'services.dailyFeature5': 'ביקור במעיינות צלולים',
    'services.dailyFeature6': 'ארוחה כלולה באזור',
    'services.dailyHighlight1': 'משך הסיור: 7-8 שעות',
    'services.dailyHighlight2': 'מתאים לגילאי 8-88+',
    'services.dailyHighlight3': 'כולל מדריך לא כולל הסעות',
    'services.dailyCTA': 'בחר את הסיור שלך',
    'services.vipTitle': 'סיורי VIP',
    'services.vipShort': 'חוויה פרימיום מותאמת אישית עם שירות יוקרתי',
    'services.vipLong': 'סיור אקסקלוסיבי ומותאם באופן מלא לרצונותיכם. שירות אישי, רכבי יוקרה, וחוויות קולינריות ברמה הגבוהה ביותר.',
    'services.vipFeature1': 'מסלול מותאם אישית 100%',
    'services.vipFeature2': 'רכבי יוקרה פרטיים עם נהג',
    'services.vipFeature3': 'חוויות קולינריות בוטיק ייחודיות',
    'services.vipFeature4': 'מדריך פרטי צמוד לאורך כל הסיור',
    'services.vipFeature5': 'גישה לאתרים ייחודיים',
    'services.vipFeature6': 'שירות קונסיירז\' מלא',
    'services.vipHighlight1': '1-45 משתתפים',
    'services.vipHighlight2': 'תיאום מלא לפי לוח הזמנים שלכם',
    'services.vipHighlight3': 'אפשרות לשילוב לינה',
    'services.vipCTA': 'תכנן סיור VIP',
    'services.odtTitle': 'ODT לארגונים',
    'services.odtShort': 'פיתוח ארגוני בחוץ - גיבוש וצוות לחברות',
    'services.odtLong': 'תוכנית ODT מקצועית המשלבת אתגרים, פעילויות גיבוש, וחוויות בטבע. מתאים לחברות בכל הגדלים.',
    'services.odtFeature1': 'תכנון אירוע מותאם לצרכי הארגון',
    'services.odtFeature2': 'פעילויות גיבוש מקצועיות ומנחים מוסמכים',
    'services.odtFeature3': 'מתאים לקבוצות 10-200 משתתפים',
    'services.odtFeature4': 'שילוב בין פעילות גופנית לתוכן ערכי',
    'services.odtFeature5': 'דגש על עבודת צוות ומנהיגות',
    'services.odtFeature6': 'אפשרות לשילוב הרצאות וסדנאות',
    'services.odtHighlight1': 'משך האירוע: חצי יום עד יומיים',
    'services.odtHighlight2': 'כולל ציוד מקצועי',
    'services.odtHighlight3': 'צוות מדריכים וצוות תמיכה',
    'services.odtCTA': 'צור קשר לתכנון',
    'services.whatIncluded': 'מה כולל?',
    'services.keyPoints': 'נקודות מרכזיות',
    'services.clickDetails': 'לחץ לפרטים מלאים',

    // Testimonials
    'testimonials.title': 'מה הלקוחות שלנו אומרים',
    'testimonials.subtitle': 'אלפי חברות סומכות עלינו ליצירת חוויות בלתי נשכחות',
    'testimonials.featured': '⭐ המלצה מודגשת',

    // Booking
    'booking.title': 'הזמנת סיור',
    'booking.subtitle': 'מלא את הפרטים ונציג יצור איתך קשר',
    'booking.name': 'שם מלא *',
    'booking.email': 'אימייל *',
    'booking.phone': 'טלפון *',
    'booking.company': 'חברה (אופציונלי)',
    'booking.participants': 'מספר משתתפים *',
    'booking.tourDate': 'תאריך הסיור *',
    'booking.selectDate': 'בחר תאריך',
    'booking.duration': 'משך הסיור *',
    'booking.selectDuration': 'בחר משך',
    'booking.halfDay': 'חצי יום (4 שעות)',
    'booking.fullDay': 'יום מלא (8 שעות)',
    'booking.twoDays': 'יומיים',
    'booking.threeDays': '3 ימים',
    'booking.custom': 'מותאם אישית',
    'booking.language': 'שפת המדריך *',
    'booking.selectLanguage': 'בחר שפה',
    'booking.specialRequests': 'בקשות מיוחדות (אופציונלי)',
    'booking.specialPlaceholder': 'מה ברצונכם לחוות, לראות, לצפות בסיור?',
    'booking.submit': 'שלח הזמנה',
    'booking.submitting': 'שולח...',
    'booking.success': 'ההזמנה נשלחה בהצלחה!',
    'booking.successDesc': 'נציג יצור איתך קשר בהקדם',
    'booking.error': 'שגיאה',
    'booking.errorDesc': 'אירעה שגיאה בשליחת ההזמנה. נסה שוב.',
    'booking.dateError': 'נא לבחור תאריך לסיור',

    // MegaMenu
    'mega.home.desc': 'גלה את הגלבוע והעמק הירדן',
    'mega.home.h1': 'נופים פנורמיים',
    'mega.home.h2': 'חוויות ייחודיות',
    'mega.home.h3': 'מקצועיות ואיכות',
    'mega.funDay.desc': 'יום מלא בפעילויות מגבשות',
    'mega.funDay.h1': '100+ פעילויות',
    'mega.funDay.h2': 'Quiz מותאם אישית',
    'mega.funDay.h3': 'חוויות בטבע',
    'mega.vip.desc': 'חוויות VIP מותאמות אישית',
    'mega.vip.h1': 'שירות יוקרתי',
    'mega.vip.h2': 'מדריכי שפות',
    'mega.vip.h3': 'התאמה אישית',
    'mega.odt.desc': 'תוכניות גיבוש צוותיות מתקדמות',
    'mega.odt.h1': 'בניית צוות',
    'mega.odt.h2': 'אתגרים מקצועיים',
    'mega.odt.h3': 'חוויה משמעותית',
    'mega.contact.desc': 'נשמח לעזור ולייעץ',
    'mega.contact.h1': 'שירות אישי',
    'mega.contact.h2': 'מענה מהיר',
    'mega.contact.h3': 'ייעוץ מקצועי',
    'mega.goTo': 'עבור ל',

    // Exit Intent Modal
    'exit.title': 'יש שאלות?',
    'exit.needAdvice': '?צריכים ייעוץ נוסף',
    'exit.speakWith': 'דברו ישירות עם',
    'exit.expertAvailable': 'מומחה הטיולים שלנו - זמין עכשיו!',
    'exit.whatsapp': 'שלחו הודעה בוואטסאפ עכשיו',
    'exit.callDirect': 'התקשרו ישירות:',
    'exit.sendEmail': 'שלחו אימייל',
    'exit.continueBrowsing': 'אמשיך לגלוש באתר',
    'exit.helpTip': '💡 אנחנו כאן כדי לעזור! אל תהססו לפנות בכל שאלה',

    // Emergency Contact
    'emergency.talkToOwner': 'דברו עם הבעלים',
    'emergency.needHelp': 'צריכים עזרה? דברו איתי!',
    'emergency.availableNow': 'זמין עכשיו',
    'emergency.tourExpert': 'מומחה הטיולים שלנו',
    'emergency.personalMessage': '💬 אני כאן בשבילכם! אם יש שאלות, רוצים ליווי באתר יחד איתי? רוצים ייעוץ אישי - אל תהססו לפנות אליי ישירות. אענה בשמחה!',
    'emergency.contactMethods': 'דרכי התקשרות:',
    'emergency.whatsapp': 'שלחו הודעה בוואטסאפ',
    'emergency.whatsappSub': 'מומלץ - תגובה מהירה!',
    'emergency.callDirect': 'התקשרו ישירות',
    'emergency.sendEmail': 'שלחו אימייל',
    'emergency.availability': 'זמני זמינות',
    'emergency.sunThur': 'ימים א׳-ה׳: 08:00-20:00',
    'emergency.friday': 'יום ו׳: 08:00-14:00',
    'emergency.urgent': 'במקרים דחופים - גם מחוץ לשעות אלו!',
    'emergency.goal': '🎯 המטרה שלי: שתמצאו את החוויה המושלמת!',

    // Protected Route
    'protected.loading': 'טוען...',
    'protected.redirecting': 'מפנה להתחברות...',
    'protected.noPermission': 'אין הרשאה',
    'protected.noAdminAccess': 'אין לך הרשאות מנהל לצפות בדף זה',

    // Testimonial Submission Form
    'testimonialForm.title': 'שתף את החוויה שלך',
    'testimonialForm.subtitle': 'נשמח לשמוע על הטיול שלך איתנו',
    'testimonialForm.name': 'שם מלא *',
    'testimonialForm.namePlaceholder': 'שם מלא',
    'testimonialForm.email': 'אימייל',
    'testimonialForm.company': 'חברה',
    'testimonialForm.companyPlaceholder': 'שם החברה',
    'testimonialForm.tourType': 'סוג הטיול',
    'testimonialForm.tourTypePlaceholder': 'לדוגמה: טיול גיבוש, VIP, ODT',
    'testimonialForm.rating': 'דירוג *',
    'testimonialForm.testimonial': 'המלצה *',
    'testimonialForm.testimonialPlaceholder': 'ספר לנו על החוויה שלך...',
    'testimonialForm.submit': 'שלח המלצה',
    'testimonialForm.submitting': 'שולח...',
    'testimonialForm.success': 'תודה רבה!',
    'testimonialForm.successDesc': 'ההמלצה נשלחה בהצלחה ותתפרסם לאחר אישור.',
    'testimonialForm.error': 'שגיאה',
    'testimonialForm.errorDesc': 'אירעה שגיאה בשליחת ההמלצה. אנא נסה שוב.',

    // Accessibility Widget
    'a11y.skipToContent': 'דלג לתוכן הראשי',
    'a11y.openMenu': 'פתח תפריט נגישות',
    'a11y.settings': 'הגדרות נגישות',
    'a11y.fontSize': 'גודל טקסט',
    'a11y.decreaseFont': 'הקטן טקסט',
    'a11y.increaseFont': 'הגדל טקסט',
    'a11y.highContrast': 'ניגודיות גבוהה',
    'a11y.grayscale': 'גווני אפור',
    'a11y.highlightLinks': 'הדגשת קישורים',
    'a11y.stopAnimations': 'עצירת אנימציות',
    'a11y.readableFont': 'גופן קריא',
    'a11y.largeCursor': 'סמן גדול',
    'a11y.readingGuide': 'סרגל קריאה',
    'a11y.reset': 'איפוס הגדרות',
    'a11y.statement': 'הצהרת נגישות',

    // Live Chat Widget
    'liveChat.title': 'צ\'אט חי - תמיכה',
    'liveChat.connected': 'מחוברים כעת',
    'liveChat.liveChat': 'צ\'אט חי',
    'liveChat.new': 'חדש',
    'liveChat.hello': 'שלום! 👋',
    'liveChat.helpMessage': 'אנחנו כאן לעזור לכם. הזינו את שמכם להתחלת שיחה',
    'liveChat.namePlaceholder': 'השם שלכם...',
    'liveChat.startChat': 'התחל שיחה',
    'liveChat.nameRequired': 'שם נדרש',
    'liveChat.enterName': 'אנא הזינו את שמכם להתחלת שיחה',
    'liveChat.messagePlaceholder': 'כתבו הודעה...',
    'liveChat.autoResponse': '🤖 מענה אוטומטי מיידי • 👤 נציג אמיתי זמין בקרוב',
    'liveChat.agentNeeded': '📞 נציג אנושי יחזור אליכם בקרוב',
    'liveChat.agentNeededDesc': 'השאלה שלכם הועברה לנציג שלנו',
    'liveChat.sendError': 'שגיאה בשליחה',
    'liveChat.sendErrorDesc': 'לא הצלחנו לשלוח את ההודעה. אנא נסו שוב',
    'liveChat.startError': 'שגיאה',
    'liveChat.startErrorDesc': 'לא הצלחנו להתחיל את השיחה. אנא נסו שוב',
    'liveChat.nameRequiredDesc': 'אנא הזינו את שמכם להתחלת שיחה',
    'liveChat.system': 'מערכת',
    'liveChat.welcomeMessage': 'שלום {name}! 👋\n\nאנחנו כאן לעזור לכם.\n\n🤖 עונה אוטומטית חכמה תענה על שאלותיכם\n👤 נציג אמיתי יצטרף במידת הצורך\n\nאתם מוזמנים לכתוב את השאלה שלכם!',
    'liveChat.error': 'שגיאה',
    'liveChat.errorStartDesc': 'לא הצלחנו להתחיל את השיחה. אנא נסו שוב',
    'liveChat.humanAgentTitle': '📞 נציג אנושי יחזור אליכם בקרוב',
    'liveChat.humanAgentDesc': 'השאלה שלכם הועברה לנציג שלנו',

    // PublicFAQ
    'faq.title': 'שאלות נפוצות',
    'faq.subtitle': 'מצא תשובות לשאלות הנפוצות ביותר',
    'faq.loading': 'טוען שאלות נפוצות...',
    'faq.notFound': 'לא מצאת את התשובה שחיפשת?',
    'faq.contactUs': 'צור קשר איתנו',
    'faq.general': 'כללי',

    // Auth
    'auth.loading': 'טוען...',
    'auth.title': 'שמחה — מערכת ניהול',
    'auth.subtitle': 'התחבר או הירשם כדי לגשת למערכת',
    'auth.loginTab': 'התחברות',
    'auth.signupTab': 'הרשמה',
    'auth.email': 'אימייל',
    'auth.password': 'סיסמה',
    'auth.fullName': 'שם מלא',
    'auth.loginButton': 'התחבר',
    'auth.loggingIn': 'מתחבר...',
    'auth.signupButton': 'הירשם',
    'auth.signingUp': 'נרשם...',
    'auth.namePlaceholder': 'יוסי כהן',
    'auth.passwordPlaceholder': 'לפחות 6 תווים',
    'auth.invalidEmail': 'כתובת אימייל לא תקינה',
    'auth.passwordMin': 'סיסמה חייבת להכיל לפחות 6 תווים',
    'auth.nameMin': 'שם חייב להכיל לפחות 2 תווים',

    // Accessibility Statement
    'a11yStatement.title': 'הצהרת נגישות',
    'a11yStatement.metaTitle': 'הצהרת נגישות | שמחה',
    'a11yStatement.metaDesc': 'הצהרת נגישות של אתר שמחה בהתאם לתקן הישראלי SI 5568',
    'a11yStatement.subtitle': 'שמחה מחויבים להנגשת האתר לאנשים עם מוגבלויות',
    'a11yStatement.commitmentTitle': 'מחויבות לנגישות',
    'a11yStatement.commitmentP1': 'אתר שמחה פועל להנגשת האתר לאנשים עם מוגבלויות בהתאם לתקן הישראלי SI 5568 ולהנחיות WCAG 2.1 ברמה AA.',
    'a11yStatement.commitmentP2': 'אנו מאמינים שלכל אדם יש זכות לגישה שווה למידע ולשירותים, ולכן השקענו מאמצים רבים בהנגשת האתר עבור כלל המשתמשים.',
    'a11yStatement.featuresTitle': 'אמצעי נגישות באתר',
    'a11yStatement.feature1': 'התאמת גודל הטקסט - אפשרות להגדלה והקטנה של הטקסט',
    'a11yStatement.feature2': 'מצב ניגודיות גבוהה לקריאות משופרת',
    'a11yStatement.feature3': 'מצב גווני אפור לרגישות לצבעים',
    'a11yStatement.feature4': 'הדגשת קישורים לזיהוי קל',
    'a11yStatement.feature5': 'אפשרות לעצירת אנימציות',
    'a11yStatement.feature6': 'גופן קריא - מעבר לגופן ברור יותר',
    'a11yStatement.feature7': 'סמן עכבר מוגדל',
    'a11yStatement.feature8': 'סרגל קריאה לעזרה במעקב אחר השורות',
    'a11yStatement.feature9': 'ניווט מלא באמצעות מקלדת',
    'a11yStatement.feature10': 'תיאורי תמונות (alt text) לקוראי מסך',
    'a11yStatement.feature11': 'מבנה סמנטי תקני של הדף',
    'a11yStatement.feature12': 'קישור "דלג לתוכן" לניווט מהיר',
    'a11yStatement.menuTitle': 'שימוש בתפריט הנגישות',
    'a11yStatement.menuP1': 'תפריט הנגישות נמצא בכפתור הנגישות בצד שמאל של המסך (אייקון של אדם). לחיצה על הכפתור תפתח את תפריט הנגישות בו תוכלו להפעיל או לכבות את ההגדרות השונות.',
    'a11yStatement.menuP2': 'ההגדרות נשמרות אוטומטית ויחולו גם בביקורים הבאים שלכם באתר.',
    'a11yStatement.limitationsTitle': 'מגבלות ידועות',
    'a11yStatement.limitationsP': 'למרות מאמצינו להנגיש את האתר באופן מלא, ייתכן שחלקים מסוימים עדיין אינם נגישים לחלוטין. אנו ממשיכים לעבוד על שיפור הנגישות.',
    'a11yStatement.limitation1': 'חלק מהתמונות עשויות להיות חסרות תיאור מלא',
    'a11yStatement.limitation2': 'תוכן שנוצר על ידי משתמשים (כגון המלצות) עשוי שלא להיות מונגש במלואו',
    'a11yStatement.limitation3': 'מפות אינטראקטיביות עשויות להיות מוגבלות בנגישות',
    'a11yStatement.contactTitle': 'יצירת קשר בנושא נגישות',
    'a11yStatement.contactP': 'נתקלתם בבעיית נגישות? נשמח לקבל פנייתכם ולטפל בה בהקדם:',
    'a11yStatement.lastUpdate': 'עדכון אחרון',
    'a11yStatement.lastUpdateText': 'הצהרת נגישות זו עודכנה לאחרונה בתאריך:',
    'chooseDay.title': 'יום כייף וגיבוש לחברות - כ100 טיולים ואטרקציות לבחירה',
    'chooseDay.subtitle': 'בחרו מתוך הקטגוריות את האטרקציות או האתרים המועדפים עליכם',
    'chooseDay.morningAdventure': 'הרפתקת בוקר',
    'chooseDay.springsRelax': 'הרגעת מעיינות',
    'chooseDay.heritageMeeting': 'מפגש מורשת',
    'chooseDay.culinaryCelebration': 'חגיגה קולינרית',
    'chooseDay.chronologicalTip': 'שלב אותן באופן כרונולוגי ליצירת תוכנית יום מלא (09:00 - 17:00)',
    'chooseDay.category': 'קטגוריה',
    'chooseDay.selected': 'נבחרו',
    'chooseDay.selectUpTo5': 'בחר עד 5 פעילויות, יחד נקבע את האטרקציה הכי מתאימה בהיתחשב בזמנים ואפשרויות בשטח ומזג אויר',
    'chooseDay.recommended': 'מומלץ',
    'chooseDay.showing': 'מציג',
    'chooseDay.recommendedOf': 'פעילויות מומלצות מתוך',
    'chooseDay.otherOption': 'אפשרות אחרת (אם אין ברשימה):',
    'chooseDay.otherPlaceholder': 'תאר פעילות שאינה מופיעה ברשימה...',
    'chooseDay.summaryTitle': 'סיכום הבחירות שלך ליום כיף',
    'chooseDay.summarySubtitle': 'אנא מלא את הפרטים הבאים כדי שנוכל לחזור אליך',
    'chooseDay.fullName': 'שם מלא',
    'chooseDay.fullNamePlaceholder': 'הכנס שם מלא',
    'chooseDay.emailAddress': 'כתובת אימייל',
    'chooseDay.emailPlaceholder': 'הכנס כתובת אימייל',
    'chooseDay.companyName': 'שם החברה',
    'chooseDay.companyPlaceholder': 'הכנס שם חברה',
    'chooseDay.whatsappNumber': 'מספר וואטסאפ',
    'chooseDay.whatsappPlaceholder': 'הכנס מספר וואטסאפ',
    'chooseDay.officeNumber': 'מספר משרד',
    'chooseDay.officePlaceholder': 'הכנס מספר משרד',
    'chooseDay.participantCount': 'מספר משתתפים משוער',
    'chooseDay.participantPlaceholder': 'כמה אנשים יהיו בטיול?',
    'chooseDay.tourType': 'סוג הטיול',
    'chooseDay.oneDay': 'יום אחד',
    'chooseDay.multipleDays': 'מספר ימים',
    'chooseDay.suggestedDate': 'תאריך מוצע לאירוע',
    'chooseDay.selectDatePlaceholder': 'בחר תאריך',
    'chooseDay.specialComments': 'הערות ומשאלות מיוחדות אותם מבקשים האורחים',
    'chooseDay.specialPlaceholder': 'שתף אותנו בפרטים נוספים, משאלות מיוחדות או סיבת האירוע...',
    'chooseDay.languageLabel': 'שפות: יש לציין את השפה הנדרשת לאורחים שלכם',
    'chooseDay.languagePlaceholder': 'למשל: אנגלית, ספרדית, צרפתית, גרמנית...',
    'chooseDay.sendToEmail': 'שלח למייל',
    'chooseDay.sending': 'שולח...',
    'chooseDay.missingFields': 'פרטים חסרים',
    'chooseDay.missingFieldsDesc': 'אנא מלא את כל השדות הנדרשים (שם, אימייל, חברה, ומספר וואטסאפ)',
    'chooseDay.invalidEmail': 'אימייל לא תקין',
    'chooseDay.invalidEmailDesc': 'אנא הכנס כתובת אימייל תקינה',
    'chooseDay.sentSuccess': 'נשלח בהצלחה!',
    'chooseDay.sentSuccessDesc': 'ההעדפות שלך נשלחו למייל שלנו. נחזור אליך בהקדם.',
    'chooseDay.sendError': 'שגיאה בשליחה',
    'chooseDay.sendErrorDesc': 'אירעה שגיאה בשליחת ההעדפות. נסה שוב מאוחר יותר.',
    'chooseDay.selectedForYou': 'הפעילויות נבחרו במיוחד עבורכם',
    'chooseDay.basedOnDNA': 'בהתאם ל-DNA של הצוות שלכם:',
    'chooseDay.changePreferences': 'שנה העדפות',
    'chooseDay.showAllActivities': 'הצג את כל הפעילויות',
    'chooseDay.showingAll': 'מציג את כל הפעילויות.',
    'chooseDay.backToRecommended': 'חזור לפעילויות המומלצות',
    'chooseDay.highlyRecommended': 'מומלץ מאד',
    'chooseDay.required': '*',

    // VIP Tours
    'vip.badge': 'טיולי VIP - עד 19 מטיילים',
    'vip.title': 'טיול VIP מיוחד לאורחים מחו״ל',
    'vip.description': 'החברה שלכם מארחת אורחים מחו״ל? שמחה יכול לארח אותם בטיול VIP ברכב ממוזג מפואר ולהעניק להם חוויית טיול בלתי נשכחת ברחבי ישראל.',
    'vip.features': 'מתאים לקבוצות של 1-19 מטיילים • נהג מקצועי ומדריך מומחה • רכב מפואר וממוזג • מסלולים מותאמים אישית',
    'vip.vehicleVIP': 'רכב VIP ממוזג',
    'vip.professionalGuide': 'מדריך מקצועי',
    'vip.customRoute': 'מסלול מותאם אישית',
    'vip.selectTitle': 'בחרו את חבל הארץ ואת האתרים המועדפים עליכם',
    'vip.selectSubtitle': 'רשימת 50 אתרים מומלצים לביקור בישראל, מחולקים לפי אזורים גיאוגרפיים – מצפון לדרום',
    'vip.selectNote': 'הרשימה כוללת אתרים היסטוריים, טבעיים, דתיים ותרבותיים, שנחשבים מהחשובים והמרתקים ביותר בארץ',
    'vip.selectUpTo5': 'בחר עד 5 פעילויות, יחד נקבע את האטרקציות הכי מתאימות בהיתחשב בזמנים ואפשרויות בשטח ומזג אויר',
    'vip.selectedCount': 'נבחרו',
    'vip.summaryTitle': 'סיכום הבחירות שלך לטיול VIP',
    'vip.sendToEmail': 'שלח למייל',
    'vip.sending': 'שולח...',
    'vip.sitesSelected': 'אתרים נבחרו',
    'vip.contactTitle': 'פרטי יצירת קשר',
    'vip.fullName': 'שם מלא *',
    'vip.fullNamePlaceholder': 'הכנס את שמך המלא',
    'vip.email': 'אימייל *',
    'vip.companyName': 'שם החברה *',
    'vip.companyPlaceholder': 'הכנס את שם החברה',
    'vip.whatsappNumber': 'מספר וואטסאפ *',
    'vip.officeNumber': 'מספר משרדי',
    'vip.participantCount': 'מספר משתתפים',
    'vip.participantPlaceholder': 'מספר האורחים',
    'vip.numberOfDays': 'מספר ימים',
    'vip.selectDays': 'בחר מספר ימים',
    'vip.suggestedDate': 'תאריך מוצע',
    'vip.selectDate': 'בחר תאריך',
    'vip.tourLanguage': 'שפת הטיול',
    'vip.tourLanguagePlaceholder': 'למשל: עברית, אנגלית, וכו׳',
    'vip.specialComments': 'הערות ומשאלות מיוחדות אותם מבקשים האורחים',
    'vip.specialPlaceholder': 'שתפו בפרטים, משאלות מיוחדות או סיבת האירוע...',
    'vip.missingFields': 'פרטים חסרים',
    'vip.missingFieldsDesc': 'אנא מלא את כל השדות הנדרשים (שם, אימייל, חברה, ומספר וואטסאפ)',
    'vip.invalidEmail': 'אימייל לא תקין',
    'vip.invalidEmailDesc': 'אנא הכנס כתובת אימייל תקינה',
    'vip.sentSuccess': 'ההעדפות נשלחו בהצלחה!',
    'vip.sentSuccessDesc': 'ניצור איתך קשר בהקדם',
    'vip.sendError': 'שגיאה בשליחה',
    'vip.sendErrorDesc': 'אירעה שגיאה בשליחת ההעדפות. נסה שוב מאוחר יותר.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('site-language');
    return (saved === 'en' || saved === 'he') ? saved : 'he';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('site-language', lang);
  };

  useEffect(() => {
    document.documentElement.dir = language === 'he' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'he';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
